import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Background } from "@/src/components/Layout/Background/Background";
import { LayerContextProvider } from "@/src/components/Layer/LayerContextProvider";
import NavBar from "@/src/components/NavBar/NavBar";

import type { PropsWithChildren } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootProps = PropsWithChildren;

const RootLayout: React.FC<RootProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayerContextProvider>
          <NavBar />

          {children}
          <Background />
        </LayerContextProvider>
      </body>
    </html>
  );
};

export default RootLayout;
